[package]
name = "kern"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.3.1"
x86_64 = { version = "0.15.1", default-features = false, features = ["instructions"] }
embedded-graphics = "0.8.1"
